name: Build Microcode Roms

on:
  workflow_dispatch:   # allow manual trigger
  push:
    tags:
      - 'v*'           # run when you push a tag like v1.0.0
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 this is required to create releases


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run generator.py
        working-directory: Microcode_Generator   # 👈 adjust this to the folder where generator.py lives
        run: |
          python generator.py

      - name: Run assembler.py
        working-directory: Assembler
        run: |
          python assembler.py test_program.asm test_program.hex

      - name: Collect output files
        run: |
          mkdir artifacts
          cp Microcode_Generator/*.bin artifacts/ || true
          cp Microcode_Generator/*.hex artifacts/ || true
          cp Assembler/*.hex artifacts/ || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
